### ISSUE TITLE
DbMetal: Don't know how to convert the SQL type 'xml' into a managed type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DbLinq/dblinq2007#342]
```
What steps will reproduce the problem?
1. Create Postgresql table with a column of type xml
2. Run DbMetal.exe
3. Get greeted by it not knowing how to use it.

Please provide any additional information below.

I tried adding an entry for xml in SchemaLoader.TypeMapping.cs, to map it as a 
string. I still get the same error. What other steps do I need to know in order 
to get my type mapped?
```

Original issue reported on code.google.com by `faboster` on 19 Mar 2014 at 1:13

**Comment by alexeyfadeev** [comment]
Hello. You can use my fork of DbLinq (branch: features) with xml type support and some other features
https://github.com/alexeyfadeev/dblinq2007/tree/features

**Comment by alexeyfadeev** [comment]
Merged to master: https://github.com/DbLinq/dblinq2007/commit/7a918e44109511490b0402c8aef5f9390456388b
Type 'xml' is converted into string now.
